### ISSUE TITLE
Create a power "equipment slot" system, only 2 powers simultaneously.

### ISSUE THREAD

**Issue by KapFlagon** [KapFlagon/Imoonity#64]
### Details
Update checkpoint with option to open a pop-up dialog for power selection. 
Only 2 power ups can be equipped at a time. 
We also need to create a singleton autoload class to store the selected powers in a global manner. 

### ToDo: 
- [x] Update Checkpoint scene with some code to display a pop-up UI. 
- [x] Update the HUD script so that it will hide non-equipped power-ups. 
- [x] Create the singleton autoload class, with variables for storing the active powers.
